project:
  type: website
  output-dir: docs
  
# Meta
author-meta: "Yiren Xu"

website:
  title: "Yiren (Sam) Xu"
  open-graph: true
  site-url: "https://yirenx.github.io/"
  navbar:
    background: "#7BA392"
    foreground: "light"
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: CV
        href: files/navbar/yiren-xu-cv-0725.pdf
        target: _blank          
    right:
      - icon: envelope
        href: mailto:yirenx@uci.edu 
        target: _blank    
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?hl=en&user=WwlllWgAAAAJ
        target: _blank         
      - icon: github
        href: https://github.com/yirenx
        target: _blank
    page-footer: 
      left: "[Yiren Xu](http://yirenx.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    
    reader-mode: true



format:
  html:
    theme: [simplex, style.scss]
    toc: false
    link-external-newwindow: true
    email-obfuscation: javascript



